---
chdir: .
environment: test
address: 0.0.0.0
port: 3001
timeout: 30
log: log/thin.test.log
pid: tmp/pids/thin.test.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
servers: 1
daemonize: true