require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AccountSessionsController do

  # This should return the minimal set of attributes required to create a valid
  # AccountSession. As you add validations to AccountSession, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "started_at" => "2015-01-27 11:21:13" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AccountSessionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all account_sessions as @account_sessions" do
      account_session = AccountSession.create! valid_attributes
      get :index, {}, valid_session
      assigns(:account_sessions).should eq([account_session])
    end
  end

  describe "GET show" do
    it "assigns the requested account_session as @account_session" do
      account_session = AccountSession.create! valid_attributes
      get :show, {:id => account_session.to_param}, valid_session
      assigns(:account_session).should eq(account_session)
    end
  end

  describe "GET new" do
    it "assigns a new account_session as @account_session" do
      get :new, {}, valid_session
      assigns(:account_session).should be_a_new(AccountSession)
    end
  end

  describe "GET edit" do
    it "assigns the requested account_session as @account_session" do
      account_session = AccountSession.create! valid_attributes
      get :edit, {:id => account_session.to_param}, valid_session
      assigns(:account_session).should eq(account_session)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AccountSession" do
        expect {
          post :create, {:account_session => valid_attributes}, valid_session
        }.to change(AccountSession, :count).by(1)
      end

      it "assigns a newly created account_session as @account_session" do
        post :create, {:account_session => valid_attributes}, valid_session
        assigns(:account_session).should be_a(AccountSession)
        assigns(:account_session).should be_persisted
      end

      it "redirects to the created account_session" do
        post :create, {:account_session => valid_attributes}, valid_session
        response.should redirect_to(AccountSession.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved account_session as @account_session" do
        # Trigger the behavior that occurs when invalid params are submitted
        AccountSession.any_instance.stub(:save).and_return(false)
        post :create, {:account_session => { "started_at" => "invalid value" }}, valid_session
        assigns(:account_session).should be_a_new(AccountSession)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AccountSession.any_instance.stub(:save).and_return(false)
        post :create, {:account_session => { "started_at" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested account_session" do
        account_session = AccountSession.create! valid_attributes
        # Assuming there are no other account_sessions in the database, this
        # specifies that the AccountSession created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AccountSession.any_instance.should_receive(:update_attributes).with({ "started_at" => "2015-01-27 11:21:13" })
        put :update, {:id => account_session.to_param, :account_session => { "started_at" => "2015-01-27 11:21:13" }}, valid_session
      end

      it "assigns the requested account_session as @account_session" do
        account_session = AccountSession.create! valid_attributes
        put :update, {:id => account_session.to_param, :account_session => valid_attributes}, valid_session
        assigns(:account_session).should eq(account_session)
      end

      it "redirects to the account_session" do
        account_session = AccountSession.create! valid_attributes
        put :update, {:id => account_session.to_param, :account_session => valid_attributes}, valid_session
        response.should redirect_to(account_session)
      end
    end

    describe "with invalid params" do
      it "assigns the account_session as @account_session" do
        account_session = AccountSession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AccountSession.any_instance.stub(:save).and_return(false)
        put :update, {:id => account_session.to_param, :account_session => { "started_at" => "invalid value" }}, valid_session
        assigns(:account_session).should eq(account_session)
      end

      it "re-renders the 'edit' template" do
        account_session = AccountSession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AccountSession.any_instance.stub(:save).and_return(false)
        put :update, {:id => account_session.to_param, :account_session => { "started_at" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested account_session" do
      account_session = AccountSession.create! valid_attributes
      expect {
        delete :destroy, {:id => account_session.to_param}, valid_session
      }.to change(AccountSession, :count).by(-1)
    end

    it "redirects to the account_sessions list" do
      account_session = AccountSession.create! valid_attributes
      delete :destroy, {:id => account_session.to_param}, valid_session
      response.should redirect_to(account_sessions_url)
    end
  end

end
