require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BotVersionsController do

  # This should return the minimal set of attributes required to create a valid
  # BotVersion. As you add validations to BotVersion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "version" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BotVersionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all bot_versions as @bot_versions" do
      bot_version = BotVersion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bot_versions).should eq([bot_version])
    end
  end

  describe "GET show" do
    it "assigns the requested bot_version as @bot_version" do
      bot_version = BotVersion.create! valid_attributes
      get :show, {:id => bot_version.to_param}, valid_session
      assigns(:bot_version).should eq(bot_version)
    end
  end

  describe "GET new" do
    it "assigns a new bot_version as @bot_version" do
      get :new, {}, valid_session
      assigns(:bot_version).should be_a_new(BotVersion)
    end
  end

  describe "GET edit" do
    it "assigns the requested bot_version as @bot_version" do
      bot_version = BotVersion.create! valid_attributes
      get :edit, {:id => bot_version.to_param}, valid_session
      assigns(:bot_version).should eq(bot_version)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BotVersion" do
        expect {
          post :create, {:bot_version => valid_attributes}, valid_session
        }.to change(BotVersion, :count).by(1)
      end

      it "assigns a newly created bot_version as @bot_version" do
        post :create, {:bot_version => valid_attributes}, valid_session
        assigns(:bot_version).should be_a(BotVersion)
        assigns(:bot_version).should be_persisted
      end

      it "redirects to the created bot_version" do
        post :create, {:bot_version => valid_attributes}, valid_session
        response.should redirect_to(BotVersion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bot_version as @bot_version" do
        # Trigger the behavior that occurs when invalid params are submitted
        BotVersion.any_instance.stub(:save).and_return(false)
        post :create, {:bot_version => { "version" => "invalid value" }}, valid_session
        assigns(:bot_version).should be_a_new(BotVersion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BotVersion.any_instance.stub(:save).and_return(false)
        post :create, {:bot_version => { "version" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bot_version" do
        bot_version = BotVersion.create! valid_attributes
        # Assuming there are no other bot_versions in the database, this
        # specifies that the BotVersion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BotVersion.any_instance.should_receive(:update_attributes).with({ "version" => "MyString" })
        put :update, {:id => bot_version.to_param, :bot_version => { "version" => "MyString" }}, valid_session
      end

      it "assigns the requested bot_version as @bot_version" do
        bot_version = BotVersion.create! valid_attributes
        put :update, {:id => bot_version.to_param, :bot_version => valid_attributes}, valid_session
        assigns(:bot_version).should eq(bot_version)
      end

      it "redirects to the bot_version" do
        bot_version = BotVersion.create! valid_attributes
        put :update, {:id => bot_version.to_param, :bot_version => valid_attributes}, valid_session
        response.should redirect_to(bot_version)
      end
    end

    describe "with invalid params" do
      it "assigns the bot_version as @bot_version" do
        bot_version = BotVersion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BotVersion.any_instance.stub(:save).and_return(false)
        put :update, {:id => bot_version.to_param, :bot_version => { "version" => "invalid value" }}, valid_session
        assigns(:bot_version).should eq(bot_version)
      end

      it "re-renders the 'edit' template" do
        bot_version = BotVersion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BotVersion.any_instance.stub(:save).and_return(false)
        put :update, {:id => bot_version.to_param, :bot_version => { "version" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bot_version" do
      bot_version = BotVersion.create! valid_attributes
      expect {
        delete :destroy, {:id => bot_version.to_param}, valid_session
      }.to change(BotVersion, :count).by(-1)
    end

    it "redirects to the bot_versions list" do
      bot_version = BotVersion.create! valid_attributes
      delete :destroy, {:id => bot_version.to_param}, valid_session
      response.should redirect_to(bot_versions_url)
    end
  end

end
