require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DirectGoldAgentsController do

  # This should return the minimal set of attributes required to create a valid
  # DirectGoldAgent. As you add validations to DirectGoldAgent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "server_id" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DirectGoldAgentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all direct_gold_agents as @direct_gold_agents" do
      direct_gold_agent = DirectGoldAgent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:direct_gold_agents).should eq([direct_gold_agent])
    end
  end

  describe "GET show" do
    it "assigns the requested direct_gold_agent as @direct_gold_agent" do
      direct_gold_agent = DirectGoldAgent.create! valid_attributes
      get :show, {:id => direct_gold_agent.to_param}, valid_session
      assigns(:direct_gold_agent).should eq(direct_gold_agent)
    end
  end

  describe "GET new" do
    it "assigns a new direct_gold_agent as @direct_gold_agent" do
      get :new, {}, valid_session
      assigns(:direct_gold_agent).should be_a_new(DirectGoldAgent)
    end
  end

  describe "GET edit" do
    it "assigns the requested direct_gold_agent as @direct_gold_agent" do
      direct_gold_agent = DirectGoldAgent.create! valid_attributes
      get :edit, {:id => direct_gold_agent.to_param}, valid_session
      assigns(:direct_gold_agent).should eq(direct_gold_agent)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DirectGoldAgent" do
        expect {
          post :create, {:direct_gold_agent => valid_attributes}, valid_session
        }.to change(DirectGoldAgent, :count).by(1)
      end

      it "assigns a newly created direct_gold_agent as @direct_gold_agent" do
        post :create, {:direct_gold_agent => valid_attributes}, valid_session
        assigns(:direct_gold_agent).should be_a(DirectGoldAgent)
        assigns(:direct_gold_agent).should be_persisted
      end

      it "redirects to the created direct_gold_agent" do
        post :create, {:direct_gold_agent => valid_attributes}, valid_session
        response.should redirect_to(DirectGoldAgent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved direct_gold_agent as @direct_gold_agent" do
        # Trigger the behavior that occurs when invalid params are submitted
        DirectGoldAgent.any_instance.stub(:save).and_return(false)
        post :create, {:direct_gold_agent => { "server_id" => "invalid value" }}, valid_session
        assigns(:direct_gold_agent).should be_a_new(DirectGoldAgent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DirectGoldAgent.any_instance.stub(:save).and_return(false)
        post :create, {:direct_gold_agent => { "server_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested direct_gold_agent" do
        direct_gold_agent = DirectGoldAgent.create! valid_attributes
        # Assuming there are no other direct_gold_agents in the database, this
        # specifies that the DirectGoldAgent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DirectGoldAgent.any_instance.should_receive(:update_attributes).with({ "server_id" => "MyString" })
        put :update, {:id => direct_gold_agent.to_param, :direct_gold_agent => { "server_id" => "MyString" }}, valid_session
      end

      it "assigns the requested direct_gold_agent as @direct_gold_agent" do
        direct_gold_agent = DirectGoldAgent.create! valid_attributes
        put :update, {:id => direct_gold_agent.to_param, :direct_gold_agent => valid_attributes}, valid_session
        assigns(:direct_gold_agent).should eq(direct_gold_agent)
      end

      it "redirects to the direct_gold_agent" do
        direct_gold_agent = DirectGoldAgent.create! valid_attributes
        put :update, {:id => direct_gold_agent.to_param, :direct_gold_agent => valid_attributes}, valid_session
        response.should redirect_to(direct_gold_agent)
      end
    end

    describe "with invalid params" do
      it "assigns the direct_gold_agent as @direct_gold_agent" do
        direct_gold_agent = DirectGoldAgent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DirectGoldAgent.any_instance.stub(:save).and_return(false)
        put :update, {:id => direct_gold_agent.to_param, :direct_gold_agent => { "server_id" => "invalid value" }}, valid_session
        assigns(:direct_gold_agent).should eq(direct_gold_agent)
      end

      it "re-renders the 'edit' template" do
        direct_gold_agent = DirectGoldAgent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DirectGoldAgent.any_instance.stub(:save).and_return(false)
        put :update, {:id => direct_gold_agent.to_param, :direct_gold_agent => { "server_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested direct_gold_agent" do
      direct_gold_agent = DirectGoldAgent.create! valid_attributes
      expect {
        delete :destroy, {:id => direct_gold_agent.to_param}, valid_session
      }.to change(DirectGoldAgent, :count).by(-1)
    end

    it "redirects to the direct_gold_agents list" do
      direct_gold_agent = DirectGoldAgent.create! valid_attributes
      delete :destroy, {:id => direct_gold_agent.to_param}, valid_session
      response.should redirect_to(direct_gold_agents_url)
    end
  end

end
