require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GoldAgentAllocationsController do

  # This should return the minimal set of attributes required to create a valid
  # GoldAgentAllocation. As you add validations to GoldAgentAllocation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "new" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GoldAgentAllocationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all gold_agent_allocations as @gold_agent_allocations" do
      gold_agent_allocation = GoldAgentAllocation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:gold_agent_allocations).should eq([gold_agent_allocation])
    end
  end

  describe "GET show" do
    it "assigns the requested gold_agent_allocation as @gold_agent_allocation" do
      gold_agent_allocation = GoldAgentAllocation.create! valid_attributes
      get :show, {:id => gold_agent_allocation.to_param}, valid_session
      assigns(:gold_agent_allocation).should eq(gold_agent_allocation)
    end
  end

  describe "GET new" do
    it "assigns a new gold_agent_allocation as @gold_agent_allocation" do
      get :new, {}, valid_session
      assigns(:gold_agent_allocation).should be_a_new(GoldAgentAllocation)
    end
  end

  describe "GET edit" do
    it "assigns the requested gold_agent_allocation as @gold_agent_allocation" do
      gold_agent_allocation = GoldAgentAllocation.create! valid_attributes
      get :edit, {:id => gold_agent_allocation.to_param}, valid_session
      assigns(:gold_agent_allocation).should eq(gold_agent_allocation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GoldAgentAllocation" do
        expect {
          post :create, {:gold_agent_allocation => valid_attributes}, valid_session
        }.to change(GoldAgentAllocation, :count).by(1)
      end

      it "assigns a newly created gold_agent_allocation as @gold_agent_allocation" do
        post :create, {:gold_agent_allocation => valid_attributes}, valid_session
        assigns(:gold_agent_allocation).should be_a(GoldAgentAllocation)
        assigns(:gold_agent_allocation).should be_persisted
      end

      it "redirects to the created gold_agent_allocation" do
        post :create, {:gold_agent_allocation => valid_attributes}, valid_session
        response.should redirect_to(GoldAgentAllocation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gold_agent_allocation as @gold_agent_allocation" do
        # Trigger the behavior that occurs when invalid params are submitted
        GoldAgentAllocation.any_instance.stub(:save).and_return(false)
        post :create, {:gold_agent_allocation => { "new" => "invalid value" }}, valid_session
        assigns(:gold_agent_allocation).should be_a_new(GoldAgentAllocation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GoldAgentAllocation.any_instance.stub(:save).and_return(false)
        post :create, {:gold_agent_allocation => { "new" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested gold_agent_allocation" do
        gold_agent_allocation = GoldAgentAllocation.create! valid_attributes
        # Assuming there are no other gold_agent_allocations in the database, this
        # specifies that the GoldAgentAllocation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GoldAgentAllocation.any_instance.should_receive(:update_attributes).with({ "new" => "MyString" })
        put :update, {:id => gold_agent_allocation.to_param, :gold_agent_allocation => { "new" => "MyString" }}, valid_session
      end

      it "assigns the requested gold_agent_allocation as @gold_agent_allocation" do
        gold_agent_allocation = GoldAgentAllocation.create! valid_attributes
        put :update, {:id => gold_agent_allocation.to_param, :gold_agent_allocation => valid_attributes}, valid_session
        assigns(:gold_agent_allocation).should eq(gold_agent_allocation)
      end

      it "redirects to the gold_agent_allocation" do
        gold_agent_allocation = GoldAgentAllocation.create! valid_attributes
        put :update, {:id => gold_agent_allocation.to_param, :gold_agent_allocation => valid_attributes}, valid_session
        response.should redirect_to(gold_agent_allocation)
      end
    end

    describe "with invalid params" do
      it "assigns the gold_agent_allocation as @gold_agent_allocation" do
        gold_agent_allocation = GoldAgentAllocation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GoldAgentAllocation.any_instance.stub(:save).and_return(false)
        put :update, {:id => gold_agent_allocation.to_param, :gold_agent_allocation => { "new" => "invalid value" }}, valid_session
        assigns(:gold_agent_allocation).should eq(gold_agent_allocation)
      end

      it "re-renders the 'edit' template" do
        gold_agent_allocation = GoldAgentAllocation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GoldAgentAllocation.any_instance.stub(:save).and_return(false)
        put :update, {:id => gold_agent_allocation.to_param, :gold_agent_allocation => { "new" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gold_agent_allocation" do
      gold_agent_allocation = GoldAgentAllocation.create! valid_attributes
      expect {
        delete :destroy, {:id => gold_agent_allocation.to_param}, valid_session
      }.to change(GoldAgentAllocation, :count).by(-1)
    end

    it "redirects to the gold_agent_allocations list" do
      gold_agent_allocation = GoldAgentAllocation.create! valid_attributes
      delete :destroy, {:id => gold_agent_allocation.to_param}, valid_session
      response.should redirect_to(gold_agent_allocations_url)
    end
  end

end
