require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IpFiltersController do

  # This should return the minimal set of attributes required to create a valid
  # IpFilter. As you add validations to IpFilter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "regex" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IpFiltersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ip_filters as @ip_filters" do
      ip_filter = IpFilter.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ip_filters).should eq([ip_filter])
    end
  end

  describe "GET show" do
    it "assigns the requested ip_filter as @ip_filter" do
      ip_filter = IpFilter.create! valid_attributes
      get :show, {:id => ip_filter.to_param}, valid_session
      assigns(:ip_filter).should eq(ip_filter)
    end
  end

  describe "GET new" do
    it "assigns a new ip_filter as @ip_filter" do
      get :new, {}, valid_session
      assigns(:ip_filter).should be_a_new(IpFilter)
    end
  end

  describe "GET edit" do
    it "assigns the requested ip_filter as @ip_filter" do
      ip_filter = IpFilter.create! valid_attributes
      get :edit, {:id => ip_filter.to_param}, valid_session
      assigns(:ip_filter).should eq(ip_filter)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IpFilter" do
        expect {
          post :create, {:ip_filter => valid_attributes}, valid_session
        }.to change(IpFilter, :count).by(1)
      end

      it "assigns a newly created ip_filter as @ip_filter" do
        post :create, {:ip_filter => valid_attributes}, valid_session
        assigns(:ip_filter).should be_a(IpFilter)
        assigns(:ip_filter).should be_persisted
      end

      it "redirects to the created ip_filter" do
        post :create, {:ip_filter => valid_attributes}, valid_session
        response.should redirect_to(IpFilter.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ip_filter as @ip_filter" do
        # Trigger the behavior that occurs when invalid params are submitted
        IpFilter.any_instance.stub(:save).and_return(false)
        post :create, {:ip_filter => { "regex" => "invalid value" }}, valid_session
        assigns(:ip_filter).should be_a_new(IpFilter)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        IpFilter.any_instance.stub(:save).and_return(false)
        post :create, {:ip_filter => { "regex" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ip_filter" do
        ip_filter = IpFilter.create! valid_attributes
        # Assuming there are no other ip_filters in the database, this
        # specifies that the IpFilter created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        IpFilter.any_instance.should_receive(:update_attributes).with({ "regex" => "MyString" })
        put :update, {:id => ip_filter.to_param, :ip_filter => { "regex" => "MyString" }}, valid_session
      end

      it "assigns the requested ip_filter as @ip_filter" do
        ip_filter = IpFilter.create! valid_attributes
        put :update, {:id => ip_filter.to_param, :ip_filter => valid_attributes}, valid_session
        assigns(:ip_filter).should eq(ip_filter)
      end

      it "redirects to the ip_filter" do
        ip_filter = IpFilter.create! valid_attributes
        put :update, {:id => ip_filter.to_param, :ip_filter => valid_attributes}, valid_session
        response.should redirect_to(ip_filter)
      end
    end

    describe "with invalid params" do
      it "assigns the ip_filter as @ip_filter" do
        ip_filter = IpFilter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IpFilter.any_instance.stub(:save).and_return(false)
        put :update, {:id => ip_filter.to_param, :ip_filter => { "regex" => "invalid value" }}, valid_session
        assigns(:ip_filter).should eq(ip_filter)
      end

      it "re-renders the 'edit' template" do
        ip_filter = IpFilter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IpFilter.any_instance.stub(:save).and_return(false)
        put :update, {:id => ip_filter.to_param, :ip_filter => { "regex" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ip_filter" do
      ip_filter = IpFilter.create! valid_attributes
      expect {
        delete :destroy, {:id => ip_filter.to_param}, valid_session
      }.to change(IpFilter, :count).by(-1)
    end

    it "redirects to the ip_filters list" do
      ip_filter = IpFilter.create! valid_attributes
      delete :destroy, {:id => ip_filter.to_param}, valid_session
      response.should redirect_to(ip_filters_url)
    end
  end

end
