require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IpRangesController do

  # This should return the minimal set of attributes required to create a valid
  # IpRange. As you add validations to IpRange, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "ip" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IpRangesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ip_ranges as @ip_ranges" do
      ip_range = IpRange.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ip_ranges).should eq([ip_range])
    end
  end

  describe "GET show" do
    it "assigns the requested ip_range as @ip_range" do
      ip_range = IpRange.create! valid_attributes
      get :show, {:id => ip_range.to_param}, valid_session
      assigns(:ip_range).should eq(ip_range)
    end
  end

  describe "GET new" do
    it "assigns a new ip_range as @ip_range" do
      get :new, {}, valid_session
      assigns(:ip_range).should be_a_new(IpRange)
    end
  end

  describe "GET edit" do
    it "assigns the requested ip_range as @ip_range" do
      ip_range = IpRange.create! valid_attributes
      get :edit, {:id => ip_range.to_param}, valid_session
      assigns(:ip_range).should eq(ip_range)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IpRange" do
        expect {
          post :create, {:ip_range => valid_attributes}, valid_session
        }.to change(IpRange, :count).by(1)
      end

      it "assigns a newly created ip_range as @ip_range" do
        post :create, {:ip_range => valid_attributes}, valid_session
        assigns(:ip_range).should be_a(IpRange)
        assigns(:ip_range).should be_persisted
      end

      it "redirects to the created ip_range" do
        post :create, {:ip_range => valid_attributes}, valid_session
        response.should redirect_to(IpRange.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ip_range as @ip_range" do
        # Trigger the behavior that occurs when invalid params are submitted
        IpRange.any_instance.stub(:save).and_return(false)
        post :create, {:ip_range => { "ip" => "invalid value" }}, valid_session
        assigns(:ip_range).should be_a_new(IpRange)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        IpRange.any_instance.stub(:save).and_return(false)
        post :create, {:ip_range => { "ip" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ip_range" do
        ip_range = IpRange.create! valid_attributes
        # Assuming there are no other ip_ranges in the database, this
        # specifies that the IpRange created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        IpRange.any_instance.should_receive(:update_attributes).with({ "ip" => "MyString" })
        put :update, {:id => ip_range.to_param, :ip_range => { "ip" => "MyString" }}, valid_session
      end

      it "assigns the requested ip_range as @ip_range" do
        ip_range = IpRange.create! valid_attributes
        put :update, {:id => ip_range.to_param, :ip_range => valid_attributes}, valid_session
        assigns(:ip_range).should eq(ip_range)
      end

      it "redirects to the ip_range" do
        ip_range = IpRange.create! valid_attributes
        put :update, {:id => ip_range.to_param, :ip_range => valid_attributes}, valid_session
        response.should redirect_to(ip_range)
      end
    end

    describe "with invalid params" do
      it "assigns the ip_range as @ip_range" do
        ip_range = IpRange.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IpRange.any_instance.stub(:save).and_return(false)
        put :update, {:id => ip_range.to_param, :ip_range => { "ip" => "invalid value" }}, valid_session
        assigns(:ip_range).should eq(ip_range)
      end

      it "re-renders the 'edit' template" do
        ip_range = IpRange.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IpRange.any_instance.stub(:save).and_return(false)
        put :update, {:id => ip_range.to_param, :ip_range => { "ip" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ip_range" do
      ip_range = IpRange.create! valid_attributes
      expect {
        delete :destroy, {:id => ip_range.to_param}, valid_session
      }.to change(IpRange, :count).by(-1)
    end

    it "redirects to the ip_ranges list" do
      ip_range = IpRange.create! valid_attributes
      delete :destroy, {:id => ip_range.to_param}, valid_session
      response.should redirect_to(ip_ranges_url)
    end
  end

end
