require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RoleSessionsController do

  # This should return the minimal set of attributes required to create a valid
  # RoleSession. As you add validations to RoleSession, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { FactoryGirl.attributes_for(:role_session) }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RoleSessionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }
  login_admin
  describe "GET index" do
    it "assigns all role_sessions as @role_sessions" do
      role_session = RoleSession.create! valid_attributes
      get :index, {}#, valid_session
      #assigns(:role_sessions).should eq([role_session])
    end
  end

  describe "GET show" do
    it "assigns the requested role_session as @role_session" do
      role_session = RoleSession.create! valid_attributes
      get :show, {:id => role_session.to_param}#, valid_session
      assigns(:role_session).should eq(role_session)
    end
  end

  describe "GET new" do
    it "assigns a new role_session as @role_session" do
      get :new, {}#, valid_session
      assigns(:role_session).should be_a_new(RoleSession)
    end
  end

  describe "GET edit" do
    it "assigns the requested role_session as @role_session" do
      role_session = RoleSession.create! valid_attributes
      get :edit, {:id => role_session.to_param}#, valid_session
      assigns(:role_session).should eq(role_session)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RoleSession" do
        expect {
          post :create, {:role_session => valid_attributes}#, valid_session
        }.to change(RoleSession, :count).by(1)
      end

      it "assigns a newly created role_session as @role_session" do
        post :create, {:role_session => valid_attributes}#, valid_session
        assigns(:role_session).should be_a(RoleSession)
        assigns(:role_session).should be_persisted
      end

      it "redirects to the created role_session" do
        post :create, {:role_session => valid_attributes}#, valid_session
        response.should redirect_to(RoleSession.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved role_session as @role_session" do
        # Trigger the behavior that occurs when invalid params are submitted
        RoleSession.any_instance.stub(:save).and_return(false)
        post :create, {:role_session => { "role_id" => "invalid value" }}#, valid_session
        assigns(:role_session).should be_a_new(RoleSession)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RoleSession.any_instance.stub(:save).and_return(false)
        post :create, {:role_session => { "role_id" => "invalid value" }}#, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested role_session" do
        role_session = RoleSession.create! valid_attributes
        # Assuming there are no other role_sessions in the database, this
        # specifies that the RoleSession created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RoleSession.any_instance.should_receive(:update_attributes).with({ "role_id" => "1" })
        put :update, {:id => role_session.to_param, :role_session => { "role_id" => "1" }}#, valid_session
      end

      it "assigns the requested role_session as @role_session" do
        role_session = RoleSession.create! valid_attributes
        put :update, {:id => role_session.to_param, :role_session => valid_attributes}#, valid_session
        assigns(:role_session).should eq(role_session)
      end

      it "redirects to the role_session" do
        role_session = RoleSession.create! valid_attributes
        put :update, {:id => role_session.to_param, :role_session => valid_attributes}#, valid_session
        response.should redirect_to(role_session)
      end
    end

    describe "with invalid params" do
      it "assigns the role_session as @role_session" do
        role_session = RoleSession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RoleSession.any_instance.stub(:save).and_return(false)
        put :update, {:id => role_session.to_param, :role_session => { "role_id" => "invalid value" }}#, valid_session
        assigns(:role_session).should eq(role_session)
      end

      it "re-renders the 'edit' template" do
        role_session = RoleSession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RoleSession.any_instance.stub(:save).and_return(false)
        put :update, {:id => role_session.to_param, :role_session => { "role_id" => "invalid value" }}#, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested role_session" do
      role_session = RoleSession.create! valid_attributes
      expect {
        delete :destroy, {:id => role_session.to_param}#, valid_session
      }.to change(RoleSession, :count).by(-1)
    end

    it "redirects to the role_sessions list" do
      role_session = RoleSession.create! valid_attributes
      delete :destroy, {:id => role_session.to_param}#, valid_session
      response.should redirect_to(role_sessions_url)
    end
  end

end
