require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SupportRolesController do

  # This should return the minimal set of attributes required to create a valid
  # SupportRole. As you add validations to SupportRole, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SupportRolesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all support_roles as @support_roles" do
      support_role = SupportRole.create! valid_attributes
      get :index, {}, valid_session
      assigns(:support_roles).should eq([support_role])
    end
  end

  describe "GET show" do
    it "assigns the requested support_role as @support_role" do
      support_role = SupportRole.create! valid_attributes
      get :show, {:id => support_role.to_param}, valid_session
      assigns(:support_role).should eq(support_role)
    end
  end

  describe "GET new" do
    it "assigns a new support_role as @support_role" do
      get :new, {}, valid_session
      assigns(:support_role).should be_a_new(SupportRole)
    end
  end

  describe "GET edit" do
    it "assigns the requested support_role as @support_role" do
      support_role = SupportRole.create! valid_attributes
      get :edit, {:id => support_role.to_param}, valid_session
      assigns(:support_role).should eq(support_role)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SupportRole" do
        expect {
          post :create, {:support_role => valid_attributes}, valid_session
        }.to change(SupportRole, :count).by(1)
      end

      it "assigns a newly created support_role as @support_role" do
        post :create, {:support_role => valid_attributes}, valid_session
        assigns(:support_role).should be_a(SupportRole)
        assigns(:support_role).should be_persisted
      end

      it "redirects to the created support_role" do
        post :create, {:support_role => valid_attributes}, valid_session
        response.should redirect_to(SupportRole.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved support_role as @support_role" do
        # Trigger the behavior that occurs when invalid params are submitted
        SupportRole.any_instance.stub(:save).and_return(false)
        post :create, {:support_role => { "name" => "invalid value" }}, valid_session
        assigns(:support_role).should be_a_new(SupportRole)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SupportRole.any_instance.stub(:save).and_return(false)
        post :create, {:support_role => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested support_role" do
        support_role = SupportRole.create! valid_attributes
        # Assuming there are no other support_roles in the database, this
        # specifies that the SupportRole created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SupportRole.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => support_role.to_param, :support_role => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested support_role as @support_role" do
        support_role = SupportRole.create! valid_attributes
        put :update, {:id => support_role.to_param, :support_role => valid_attributes}, valid_session
        assigns(:support_role).should eq(support_role)
      end

      it "redirects to the support_role" do
        support_role = SupportRole.create! valid_attributes
        put :update, {:id => support_role.to_param, :support_role => valid_attributes}, valid_session
        response.should redirect_to(support_role)
      end
    end

    describe "with invalid params" do
      it "assigns the support_role as @support_role" do
        support_role = SupportRole.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SupportRole.any_instance.stub(:save).and_return(false)
        put :update, {:id => support_role.to_param, :support_role => { "name" => "invalid value" }}, valid_session
        assigns(:support_role).should eq(support_role)
      end

      it "re-renders the 'edit' template" do
        support_role = SupportRole.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SupportRole.any_instance.stub(:save).and_return(false)
        put :update, {:id => support_role.to_param, :support_role => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested support_role" do
      support_role = SupportRole.create! valid_attributes
      expect {
        delete :destroy, {:id => support_role.to_param}, valid_session
      }.to change(SupportRole, :count).by(-1)
    end

    it "redirects to the support_roles list" do
      support_role = SupportRole.create! valid_attributes
      delete :destroy, {:id => support_role.to_param}, valid_session
      response.should redirect_to(support_roles_url)
    end
  end

end
