require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TicketRecordsController do

  # This should return the minimal set of attributes required to create a valid
  # TicketRecord. As you add validations to TicketRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "account" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TicketRecordsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ticket_records as @ticket_records" do
      ticket_record = TicketRecord.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ticket_records).should eq([ticket_record])
    end
  end

  describe "GET show" do
    it "assigns the requested ticket_record as @ticket_record" do
      ticket_record = TicketRecord.create! valid_attributes
      get :show, {:id => ticket_record.to_param}, valid_session
      assigns(:ticket_record).should eq(ticket_record)
    end
  end

  describe "GET new" do
    it "assigns a new ticket_record as @ticket_record" do
      get :new, {}, valid_session
      assigns(:ticket_record).should be_a_new(TicketRecord)
    end
  end

  describe "GET edit" do
    it "assigns the requested ticket_record as @ticket_record" do
      ticket_record = TicketRecord.create! valid_attributes
      get :edit, {:id => ticket_record.to_param}, valid_session
      assigns(:ticket_record).should eq(ticket_record)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TicketRecord" do
        expect {
          post :create, {:ticket_record => valid_attributes}, valid_session
        }.to change(TicketRecord, :count).by(1)
      end

      it "assigns a newly created ticket_record as @ticket_record" do
        post :create, {:ticket_record => valid_attributes}, valid_session
        assigns(:ticket_record).should be_a(TicketRecord)
        assigns(:ticket_record).should be_persisted
      end

      it "redirects to the created ticket_record" do
        post :create, {:ticket_record => valid_attributes}, valid_session
        response.should redirect_to(TicketRecord.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ticket_record as @ticket_record" do
        # Trigger the behavior that occurs when invalid params are submitted
        TicketRecord.any_instance.stub(:save).and_return(false)
        post :create, {:ticket_record => { "account" => "invalid value" }}, valid_session
        assigns(:ticket_record).should be_a_new(TicketRecord)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TicketRecord.any_instance.stub(:save).and_return(false)
        post :create, {:ticket_record => { "account" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ticket_record" do
        ticket_record = TicketRecord.create! valid_attributes
        # Assuming there are no other ticket_records in the database, this
        # specifies that the TicketRecord created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TicketRecord.any_instance.should_receive(:update_attributes).with({ "account" => "MyString" })
        put :update, {:id => ticket_record.to_param, :ticket_record => { "account" => "MyString" }}, valid_session
      end

      it "assigns the requested ticket_record as @ticket_record" do
        ticket_record = TicketRecord.create! valid_attributes
        put :update, {:id => ticket_record.to_param, :ticket_record => valid_attributes}, valid_session
        assigns(:ticket_record).should eq(ticket_record)
      end

      it "redirects to the ticket_record" do
        ticket_record = TicketRecord.create! valid_attributes
        put :update, {:id => ticket_record.to_param, :ticket_record => valid_attributes}, valid_session
        response.should redirect_to(ticket_record)
      end
    end

    describe "with invalid params" do
      it "assigns the ticket_record as @ticket_record" do
        ticket_record = TicketRecord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TicketRecord.any_instance.stub(:save).and_return(false)
        put :update, {:id => ticket_record.to_param, :ticket_record => { "account" => "invalid value" }}, valid_session
        assigns(:ticket_record).should eq(ticket_record)
      end

      it "re-renders the 'edit' template" do
        ticket_record = TicketRecord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TicketRecord.any_instance.stub(:save).and_return(false)
        put :update, {:id => ticket_record.to_param, :ticket_record => { "account" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ticket_record" do
      ticket_record = TicketRecord.create! valid_attributes
      expect {
        delete :destroy, {:id => ticket_record.to_param}, valid_session
      }.to change(TicketRecord, :count).by(-1)
    end

    it "redirects to the ticket_records list" do
      ticket_record = TicketRecord.create! valid_attributes
      delete :destroy, {:id => ticket_record.to_param}, valid_session
      response.should redirect_to(ticket_records_url)
    end
  end

end
